# sunset-mountain-white-flowers.png
{ # AUTOGENERATED BY WPP SCRIPT
    url = "https://i.imgur.com/6Fo3b85.jpeg";
    url-blur = "https://i.imgur.com/PTVn8Ys.jpeg";
    url-dim = "https://i.imgur.com/GFPlKQX.jpeg";
}
