# /home/canoe/pix/wall/irl/landscape/autumn-yosemite-valley.jpg
{ # AUTOGENERATED BY WPP SCRIPT (SOURCED FROM ~/PIX/INDEX)
    url = "https://i.imgur.com/gyRb62i.jpeg";
    url-blur = "https://i.imgur.com/BZTv9Qa.jpeg";
    url-dim = "https://i.imgur.com/KLptKvC.jpeg";
}
