# /home/canoe/pix/wall/irl/landscape/sunset-mountain-white-flowers.png
{ # AUTOGENERATED BY WPP SCRIPT
    url = "https://i.imgur.com/3iT0Ewq.jpeg";
    url-blur = "https://i.imgur.com/1iE7iOU.jpeg";
    url-dim = "https://i.imgur.com/6UTov7D.jpeg";
}
